version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 100304
      MYSQL_DATABASE: classroom
      MYSQL_USER: admin
      MYSQL_PASSWORD: 100304
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/classroom
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 100304
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
